### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by gurqn** [e1ectron/pastels-ui#1]
I wasn't able to find that theme in package control. However, installed that from GitHub. I just would like to say thank you, looks great with adaptive UI. Thank you.

Would it be possible to also make variant especially for following hyper theme? I meant at least background color :)

https://github.com/mashaal/hyper-captain-sweetheart

**Comment by solo-s** [comment]
Hey there! Appreciate for you feedback 😊
I still waiting for accepting my [pull request](https://github.com/wbond/package_control_channel/pull/6283) to package control for 19 days. Not expected, it could be so long.

About your question: I will try the colors and let you know, when I make a decision.

**Comment by solo-s** [comment]
@gurqn I check the bg color for my theme and colors looks together not pretty well 😕 

But, I can do new theme fully based on captain-sweetheart colors.

**Comment by gurqn** [comment]
Thats completely fine i understand :) it would be too much asking that i think, i still love your pastels ui theme :-)

**Comment by solo-s** [comment]
Did you ask captain's author about sublime version?
His got Hyper and Atom. Maybe he can do sublime version too?

If not, I can do this :)

By the way, you can change bg color by yourself. 
I'm not planning to update this theme in near future, so you not lost your changes :)

1. Download and open `Pastels UI.tmTheme` in sublime as text file
2. Change value of the string in row 19 to `#212121` and save. 
3. Copy file to package folder with overwriting existing file.

**Comment by gurqn** [comment]
Thank you for that tip, I will certainly test that. By the way, it's a good idea, I'm going to ask him to see if he can do something :)
